title: 'Olivia Ross'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
url: "liv4data.github.io/portfolio"

header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true


# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
